name: Status

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    # Montly (1st day)
    - cron:  '0 0 1 * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm install
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Check links order
        run: |
          npm test
          npm run check
      - name: Check links status
        run: bundle exec awesome_bot LIST.md --allow-redirect --allow-ssl --allow 301,302,307,403,404,410 --allow-timeout --set-timeout 5 --white-list origin.com,16personalities.com,wufoo.com
